<template>
    <div>
        <Navbar/>
        <Hero/>
        <DemoProducts/>
        <HuntingJacket/>
        <WildlifePage/>
        <HuntingCamping/>
        <MountainPage/>
        <Footer/>
    </div>
</template>